package exception;

public class Test {

	public static void main(String[] args) {
		int []arr= {10,15,20};
		System.out.println(arr[0]);
		System.out.println(arr[1]);
		System.out.println(arr[2]);
		try {
		System.out.println(arr[3]);
		}catch (Exception e) {
			System.out.println("no element found in exception");
		}
	}
		

	}


